/**
 * Autogenerated base class for the Places model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places.js file.
 *
 * @module Places
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Places model
 * @namespace Base
 * @class Places
 * @static
 */
function Base () {
	return this;
}
 
module.exports = Base;

/**
 * The list of model classes
 * @property tableClasses
 * @type array
 */
Base.tableClasses = [
	"Places_AddressUnit",
	"Places_Autocomplete",
	"Places_City",
	"Places_Country",
	"Places_District",
	"Places_Hierarchy",
	"Places_Ipv4",
	"Places_Ipv6",
	"Places_Location",
	"Places_Postcode",
	"Places_Region"
];

/**
 * This method calls Db.connect() using information stored in the configuration.
 * If this has already been called, then the same db object is returned.
 * @method db
 * @return {Db} The database connection
 */
Base.db = function () {
	return Db.connect('Places');
};

/**
 * The connection name for the class
 * @method connectionName
 * @return {string} The name of the connection
 */
Base.connectionName = function() {
	return 'Places';
};

/**
 * Link to Places.AddressUnit model
 * @property AddressUnit
 * @type Places.AddressUnit
 */
Base.AddressUnit = Q.require('Places/AddressUnit');

/**
 * Link to Places.Autocomplete model
 * @property Autocomplete
 * @type Places.Autocomplete
 */
Base.Autocomplete = Q.require('Places/Autocomplete');

/**
 * Link to Places.City model
 * @property City
 * @type Places.City
 */
Base.City = Q.require('Places/City');

/**
 * Link to Places.Country model
 * @property Country
 * @type Places.Country
 */
Base.Country = Q.require('Places/Country');

/**
 * Link to Places.District model
 * @property District
 * @type Places.District
 */
Base.District = Q.require('Places/District');

/**
 * Link to Places.Hierarchy model
 * @property Hierarchy
 * @type Places.Hierarchy
 */
Base.Hierarchy = Q.require('Places/Hierarchy');

/**
 * Link to Places.Ipv4 model
 * @property Ipv4
 * @type Places.Ipv4
 */
Base.Ipv4 = Q.require('Places/Ipv4');

/**
 * Link to Places.Ipv6 model
 * @property Ipv6
 * @type Places.Ipv6
 */
Base.Ipv6 = Q.require('Places/Ipv6');

/**
 * Link to Places.Location model
 * @property Location
 * @type Places.Location
 */
Base.Location = Q.require('Places/Location');

/**
 * Link to Places.Postcode model
 * @property Postcode
 * @type Places.Postcode
 */
Base.Postcode = Q.require('Places/Postcode');

/**
 * Link to Places.Region model
 * @property Region
 * @type Places.Region
 */
Base.Region = Q.require('Places/Region');
