<?php

/**
 * @module Places
 */

/**
 * Class representing 'Address_Unit' rows in the 'Places' database.
 * Caches unit/apartment numbers for building addresses.
 * 
 * @class Places_AddressUnit
 * @extends Base_Places_AddressUnit
 */
class Places_AddressUnit extends Base_Places_AddressUnit
{
	/**
	 * @method setUp
	 */
	function setUp()
	{
		parent::setUp();
	}

	/**
	 * The autogenerated base fills an unset primary key with the empty string,
	 * but `id` is BIGINT AUTO_INCREMENT, and MySQL in strict mode rejects ''
	 * for an integer column. Drop it so the database assigns the id.
	 * @method beforeSave
	 * @param {array} $value
	 * @return {array}
	 */
	function beforeSave($value)
	{
		$value = parent::beforeSave($value);
		if (isset($value['id']) and $value['id'] === '') {
			unset($value['id']);
			unset($this->fields['id']);
		}
		return $value;
	}

	/**
	 * Get all cached units for a building address
	 * @method forAddress
	 * @static
	 * @param {string} $address
	 * @return {array} Array of unit strings, naturally sorted
	 */
	static function forAddress($address)
	{
		// fetchDbRows() needs the primary key in the projection, so select all
		// columns rather than just the three we read below.
		// Db caches by SQL within a request, so a correct() followed by a read
		// in the same request would otherwise return the pre-correction list.
		$rows = self::select()
			->where(array('address' => substr($address, 0, 500)))
			->ignoreCache()
			->fetchDbRows();

		$units = array();
		foreach ($rows as $row) {
			$units[] = $row->unit;
		}

		// Penthouses parse to a null floor, and MySQL sorts NULLs first, which
		// put PH units at the top of the building list. Order in PHP instead:
		// floors ascending, unnumbered (PH) last, natural sort within a floor.
		usort($units, function ($a, $b) {
			$fa = Places_Address::parseFloor($a);
			$fb = Places_Address::parseFloor($b);
			if ($fa === null xor $fb === null) {
				return ($fa === null) ? 1 : -1;
			}
			if ($fa !== $fb) {
				return $fa < $fb ? -1 : 1;
			}
			return strnatcasecmp($a, $b);
		});
		return $units;
	}

	/**
	 * Add a user correction — a unit that wasn't in the generated list
	 * @method correct
	 * @static
	 * @param {string} $address
	 * @param {string} $unit
	 * @param {string} [$bbl]
	 * @return {Places_AddressUnit}
	 */
	static function correct($address, $unit, $bbl = null)
	{
		$row = new self();
		$row->address = substr($address, 0, 500);
		$row->unit = substr(trim($unit), 0, 31);
		if (!$row->retrieve()) {
			$row->floor = Places_Address::parseFloor($unit);
			$row->source = 'user_correction';
			$row->bbl = $bbl;
			$row->save();
		}
		return $row;
	}

	/**
	 * Where a building's unit list came from, so callers can caveat a
	 * generated list. The lookup's own "source" says "cache" the moment
	 * anything is cached, which loses the provenance that actually matters.
	 * @method sourcesForAddress
	 * @static
	 * @param {string} $address
	 * @return {array} source => count
	 */
	static function sourcesForAddress($address)
	{
		$rows = self::select()
			->where(array('address' => substr($address, 0, 500)))
			->ignoreCache()
			->fetchDbRows();
		$counts = array();
		foreach ($rows as $row) {
			$s = $row->source;
			$counts[$s] = (isset($counts[$s]) ? $counts[$s] : 0) + 1;
		}
		return $counts;
	}
}
