/**
 * Autogenerated base class representing country rows
 * in the Places database.
 *
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places/Country.js file.
 *
 * @module Places
 */

var Q = require('Q');
var Db = Q.require('Db');
var Places = Q.require('Places');
var Row = Q.require('Db/Row');

/**
 * Base class representing 'Country' rows in the 'Places' database
 * @namespace Base.Places
 * @class Country
 * @extends Db.Row
 * @constructor
 * @param {Object} [fields={}] The fields values to initialize table row as 
 * an associative array of {column: value} pairs
 * @param {String} [fields.countryCode] defaults to ""
 * @param {String} [fields.countryCode3] defaults to null
 * @param {Integer} [fields.geonameId] defaults to 0
 * @param {Integer} [fields.numericCode] defaults to 0
 * @param {String} [fields.phoneCode] defaults to null
 * @param {String} [fields.normalizedName] defaults to null
 * @param {String} [fields.englishName] defaults to null
 * @param {String} [fields.localName] defaults to null
 * @param {String} [fields.emojiFlag] defaults to null
 * @param {Integer} [fields.area] defaults to 0
 * @param {Integer} [fields.population] defaults to 0
 * @param {String} [fields.continent] defaults to null
 * @param {String} [fields.currencyCode] defaults to null
 * @param {String} [fields.currencyName] defaults to null
 */
function Base (fields) {
	Base.constructors.apply(this, arguments);
}

Q.mixin(Base, Row);

/**
 * @property countryCode
 * @type String
 * @default ""
 * 
 */
/**
 * @property countryCode3
 * @type String
 * @default null
 * 
 */
/**
 * @property geonameId
 * @type Integer
 * @default 0
 * 
 */
/**
 * @property numericCode
 * @type Integer
 * @default 0
 * 
 */
/**
 * @property phoneCode
 * @type String
 * @default null
 * 
 */
/**
 * @property normalizedName
 * @type String
 * @default null
 * 
 */
/**
 * @property englishName
 * @type String
 * @default null
 * 
 */
/**
 * @property localName
 * @type String
 * @default null
 * 
 */
/**
 * @property emojiFlag
 * @type String
 * @default null
 * 
 */
/**
 * @property area
 * @type Integer
 * @default 0
 * 
 */
/**
 * @property population
 * @type Integer
 * @default 0
 * 
 */
/**
 * @property continent
 * @type String
 * @default null
 * 
 */
/**
 * @property currencyCode
 * @type String
 * @default null
 * 
 */
/**
 * @property currencyName
 * @type String
 * @default null
 * 
 */

/**
 * This method calls Db.connect() using information stored in the configuration.
 * If this has already been called, then the same db object is returned.
 * @method db
 * @return {Db} The database connection
 */
Base.db = function () {
	return Places.db();
};

/**
 * Retrieve the table name to use in SQL statements
 * @method table
 * @param {boolean} [withoutDbName=false] Indicates wheather table name should contain the database name
 * @return {String|Db.Expression} The table name as string optionally without database name if no table sharding was started
 * or Db.Expression object with prefix and database name templates is table was sharded
 */
Base.table = function (withoutDbName) {
	if (Q.Config.get(['Db', 'connections', 'Places', 'indexes', 'Country'], false)) {
		return new Db.Expression((withoutDbName ? '' : '{{dbname}}.')+'{{prefix}}country');
	} else {
		var conn = Db.getConnection('Places');
		var prefix = conn.prefix || '';
		var tableName = prefix + 'country';
		var dbname = Base.table.dbname;
		if (!dbname) {
			var dsn = Db.parseDsnString(conn['dsn']);
			dbname = Base.table.dbname = dsn.dbname;
		}
		return withoutDbName ? tableName : dbname + '.' + tableName;
	}
};

/**
 * The connection name for the class
 * @method connectionName
 * @return {String} The name of the connection
 */
Base.connectionName = function() {
	return 'Places';
};

/**
 * Create SELECT query to the class table
 * @method SELECT
 * @param {String|Object} [fields=null] The fields as strings, or object of {alias:field} pairs.
 *   The default is to return all fields of the table.
 * @param {String|Object} [alias=null] The tables as strings, or object of {alias:table} pairs.
 * @return {Db.Query.Mysql} The generated query
 */
Base.SELECT = function(fields, alias) {
	if (!fields) {
		fields = Base.fieldNames().map(function (fn) {
			return fn;
		}).join(',');
	}
	var q = Base.db().SELECT(fields, Base.table()+(alias ? ' '+alias : ''));
	q.className = 'Places_Country';
	return q;
};

/**
 * Create UPDATE query to the class table. Use Db.Query.Mysql.set() method to define SET clause
 * @method UPDATE
 * @param {String} [alias=null] Table alias
 * @return {Db.Query.Mysql} The generated query
 */
Base.UPDATE = function(alias) {
	var q = Base.db().UPDATE(Base.table()+(alias ? ' '+alias : ''));
	q.className = 'Places_Country';
	return q;
};

/**
 * Create DELETE query to the class table
 * @method DELETE
 * @param {Object}[table_using=null] If set, adds a USING clause with this table
 * @param {String} [alias=null] Table alias
 * @return {Db.Query.Mysql} The generated query
 */
Base.DELETE = function(table_using, alias) {
	var q = Base.db().DELETE(Base.table()+(alias ? ' '+alias : ''), table_using);
	q.className = 'Places_Country';
	return q;
};

/**
 * Create INSERT query to the class table
 * @method INSERT
 * @param {Object} [fields={}] The fields as an associative array of {column: value} pairs
 * @param {String} [alias=null] Table alias
 * @return {Db.Query.Mysql} The generated query
 */
Base.INSERT = function(fields, alias) {
	var q = Base.db().INSERT(Base.table()+(alias ? ' '+alias : ''), fields || {});
	q.className = 'Places_Country';
	return q;
};

/**
 * Create raw query with BEGIN clause.
 * You'll have to specify shards yourself when calling execute().
 * @method BEGIN
 * @param {string} [$lockType] First parameter to pass to query.begin() function
 * @return {Db.Query.Mysql} The generated query
 */
Base.BEGIN = function($lockType) {
	var q = Base.db().rawQuery('').begin($lockType);
	q.className = 'Places_Country';
	return q;
};

/**
 * Create raw query with COMMIT clause
 * You'll have to specify shards yourself when calling execute().
 * @method COMMIT
 * @return {Db.Query.Mysql} The generated query
 */
Base.COMMIT = function() {
	var q = Base.db().rawQuery('').commit();
	q.className = 'Places_Country';
	return q;
};

/**
 * Create raw query with ROLLBACK clause
 * @method ROLLBACK
 * @param {Object} criteria can be used to target the query to some shards.
 *   Otherwise you'll have to specify shards yourself when calling execute().
 * @return {Db.Query.Mysql} The generated query
 */
Base.ROLLBACK = function(criteria) {
	var q = Base.db().rawQuery('').rollback(crieria);
	q.className = 'Places_Country';
	return q;
};

/**
 * The name of the class
 * @property className
 * @type string
 */
Base.prototype.className = "Places_Country";

// Instance methods

/**
 * Create INSERT query to the class table
 * @method INSERT
 * @param {object} [fields={}] The fields as an associative array of {column: value} pairs
 * @param {string} [alias=null] Table alias
 * @return {Db.Query.Mysql} The generated query
 */
Base.prototype.setUp = function() {
	// does nothing for now
};

/**
 * Create INSERT query to the class table
 * @method INSERT
 * @param {object} [fields={}] The fields as an associative array of {column: value} pairs
 * @param {string} [alias=null] Table alias
 * @return {Db.Query.Mysql} The generated query
 */
Base.prototype.db = function () {
	return Base.db();
};

/**
 * Retrieve the table name to use in SQL statements
 * @method table
 * @param {boolean} [withoutDbName=false] Indicates wheather table name should contain the database name
 * @return {String|Db.Expression} The table name as string optionally without database name if no table sharding was started
 * or Db.Expression object with prefix and database name templates is table was sharded
 */
Base.prototype.table = function () {
	return Base.table();
};

/**
 * Retrieves primary key fields names for class table
 * @method primaryKey
 * @return {string[]} An array of field names
 */
Base.prototype.primaryKey = function () {
	return [
		"countryCode"
	];
};

/**
 * Retrieves field names for class table
 * @method fieldNames
 * @return {array} An array of field names
 */
Base.prototype.fieldNames = function () {
	return Base.fieldNames();
};

/**
 * Retrieves field names for class table
 * @method fieldNames
 * @static
 * @return {array} An array of field names
 */
Base.fieldNames = function () {
	return [
		"countryCode",
		"countryCode3",
		"geonameId",
		"numericCode",
		"phoneCode",
		"normalizedName",
		"englishName",
		"localName",
		"emojiFlag",
		"area",
		"population",
		"continent",
		"currencyCode",
		"currencyName"
	];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_countryCode
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_countryCode = function (value) {
		if (value == null) {
			value='';
		}
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".countryCode");
		if (typeof value === "string" && value.length > 2)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".countryCode");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the countryCode field
	 * @return {integer}
	 */
Base.prototype.maxSize_countryCode = function () {

		return 2;
};

	/**
	 * Returns schema information for countryCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_countryCode = function () {

return [["varchar","2","",false],false,"PRI",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_countryCode3
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_countryCode3 = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".countryCode3");
		if (typeof value === "string" && value.length > 3)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".countryCode3");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the countryCode3 field
	 * @return {integer}
	 */
Base.prototype.maxSize_countryCode3 = function () {

		return 3;
};

	/**
	 * Returns schema information for countryCode3 column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_countryCode3 = function () {

return [["varchar","3","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if integer value falls within allowed limits
 * @method beforeSet_geonameId
 * @param {integer} value
 * @return {integer} The value
 * @throws {Error} An exception is thrown if 'value' is not integer or does not fit in allowed range
 */
Base.prototype.beforeSet_geonameId = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		value = Number(value);
		if (isNaN(value) || Math.floor(value) != value) 
			throw new Error('Non-integer value being assigned to '+this.table()+".geonameId");
		if (value < -2147483648 || value > 2147483647)
			throw new Error("Out-of-range value "+JSON.stringify(value)+" being assigned to "+this.table()+".geonameId");
		return value;
};

/**
 * Returns the maximum integer that can be assigned to the geonameId field
 * @return {integer}
 */
Base.prototype.maxSize_geonameId = function () {

		return 2147483647;
};

	/**
	 * Returns schema information for geonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_geonameId = function () {

return [["int",null,null,null],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if integer value falls within allowed limits
 * @method beforeSet_numericCode
 * @param {integer} value
 * @return {integer} The value
 * @throws {Error} An exception is thrown if 'value' is not integer or does not fit in allowed range
 */
Base.prototype.beforeSet_numericCode = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		value = Number(value);
		if (isNaN(value) || Math.floor(value) != value) 
			throw new Error('Non-integer value being assigned to '+this.table()+".numericCode");
		if (value < -2147483648 || value > 2147483647)
			throw new Error("Out-of-range value "+JSON.stringify(value)+" being assigned to "+this.table()+".numericCode");
		return value;
};

/**
 * Returns the maximum integer that can be assigned to the numericCode field
 * @return {integer}
 */
Base.prototype.maxSize_numericCode = function () {

		return 2147483647;
};

	/**
	 * Returns schema information for numericCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_numericCode = function () {

return [["int",null,null,null],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_phoneCode
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_phoneCode = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".phoneCode");
		if (typeof value === "string" && value.length > 20)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".phoneCode");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the phoneCode field
	 * @return {integer}
	 */
Base.prototype.maxSize_phoneCode = function () {

		return 20;
};

	/**
	 * Returns schema information for phoneCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_phoneCode = function () {

return [["varchar","20","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_normalizedName
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_normalizedName = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".normalizedName");
		if (typeof value === "string" && value.length > 180)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".normalizedName");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the normalizedName field
	 * @return {integer}
	 */
Base.prototype.maxSize_normalizedName = function () {

		return 180;
};

	/**
	 * Returns schema information for normalizedName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_normalizedName = function () {

return [["varchar","180","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_englishName
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_englishName = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".englishName");
		if (typeof value === "string" && value.length > 180)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".englishName");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the englishName field
	 * @return {integer}
	 */
Base.prototype.maxSize_englishName = function () {

		return 180;
};

	/**
	 * Returns schema information for englishName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_englishName = function () {

return [["varchar","180","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_localName
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_localName = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".localName");
		if (typeof value === "string" && value.length > 180)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".localName");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the localName field
	 * @return {integer}
	 */
Base.prototype.maxSize_localName = function () {

		return 180;
};

	/**
	 * Returns schema information for localName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_localName = function () {

return [["varchar","180","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_emojiFlag
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_emojiFlag = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".emojiFlag");
		if (typeof value === "string" && value.length > 8)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".emojiFlag");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the emojiFlag field
	 * @return {integer}
	 */
Base.prototype.maxSize_emojiFlag = function () {

		return 8;
};

	/**
	 * Returns schema information for emojiFlag column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_emojiFlag = function () {

return [["varchar","8","",false],true,"",null];
};

/**
 * Method is called before setting the field and verifies if integer value falls within allowed limits
 * @method beforeSet_area
 * @param {integer} value
 * @return {integer} The value
 * @throws {Error} An exception is thrown if 'value' is not integer or does not fit in allowed range
 */
Base.prototype.beforeSet_area = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		value = Number(value);
		if (isNaN(value) || Math.floor(value) != value) 
			throw new Error('Non-integer value being assigned to '+this.table()+".area");
		if (value < -9.2233720368548E+18 || value > 9223372036854775807)
			throw new Error("Out-of-range value "+JSON.stringify(value)+" being assigned to "+this.table()+".area");
		return value;
};

/**
 * Returns the maximum integer that can be assigned to the area field
 * @return {integer}
 */
Base.prototype.maxSize_area = function () {

		return 9223372036854775807;
};

	/**
	 * Returns schema information for area column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_area = function () {

return [["bigint",null,null,null],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if integer value falls within allowed limits
 * @method beforeSet_population
 * @param {integer} value
 * @return {integer} The value
 * @throws {Error} An exception is thrown if 'value' is not integer or does not fit in allowed range
 */
Base.prototype.beforeSet_population = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		value = Number(value);
		if (isNaN(value) || Math.floor(value) != value) 
			throw new Error('Non-integer value being assigned to '+this.table()+".population");
		if (value < -9.2233720368548E+18 || value > 9223372036854775807)
			throw new Error("Out-of-range value "+JSON.stringify(value)+" being assigned to "+this.table()+".population");
		return value;
};

/**
 * Returns the maximum integer that can be assigned to the population field
 * @return {integer}
 */
Base.prototype.maxSize_population = function () {

		return 9223372036854775807;
};

	/**
	 * Returns schema information for population column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_population = function () {

return [["bigint",null,null,null],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_continent
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_continent = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".continent");
		if (typeof value === "string" && value.length > 2)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".continent");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the continent field
	 * @return {integer}
	 */
Base.prototype.maxSize_continent = function () {

		return 2;
};

	/**
	 * Returns schema information for continent column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_continent = function () {

return [["varchar","2","",false],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_currencyCode
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_currencyCode = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".currencyCode");
		if (typeof value === "string" && value.length > 3)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".currencyCode");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the currencyCode field
	 * @return {integer}
	 */
Base.prototype.maxSize_currencyCode = function () {

		return 3;
};

	/**
	 * Returns schema information for currencyCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_currencyCode = function () {

return [["varchar","3","",false],true,"MUL",null];
};

/**
 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
 * Optionally accept numeric value which is converted to string
 * @method beforeSet_currencyName
 * @param {string} value
 * @return {string} The value
 * @throws {Error} An exception is thrown if 'value' is not string or is exceedingly long
 */
Base.prototype.beforeSet_currencyName = function (value) {
		if (value == undefined) return value;
		if (value instanceof Db.Expression) return value;
		if (typeof value !== "string" && typeof value !== "number")
			throw new Error('Must pass a String to '+this.table()+".currencyName");
		if (typeof value === "string" && value.length > 64)
			throw new Error('Exceedingly long value being assigned to '+this.table()+".currencyName");
		return value;
};

	/**
	 * Returns the maximum string length that can be assigned to the currencyName field
	 * @return {integer}
	 */
Base.prototype.maxSize_currencyName = function () {

		return 64;
};

	/**
	 * Returns schema information for currencyName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
Base.column_currencyName = function () {

return [["varchar","64","",false],true,"",null];
};

/**
 * Check if mandatory fields are set and updates 'magic fields' with appropriate values
 * @method beforeSave
 * @param {Object} value The object of fields
 * @param {Function} callback Call this callback if you return null
 * @return {Object|null} Return the fields, modified if necessary. If you return null, then you should call the callback(err, modifiedFields)
 * @throws {Error} If e.g. mandatory field is not set or a bad values are supplied
 */
Base.prototype.beforeSave = function (value) {
	var fields = ['countryCode'], i;
	if (!this._retrieved) {
		var table = this.table();
		for (i=0; i<fields.length; i++) {
			if (this.fields[fields[i]] === undefined) {
				throw new Error("the field "+table+"."+fields[i]+" needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
			}
		}
	}
	if (this.fields["countryCode"] == undefined && value["countryCode"] == undefined) {
		this.fields["countryCode"] = value["countryCode"] = "";
	}
	return value;
};

module.exports = Base;