<?php

/**
 * Autogenerated base class representing country rows
 * in the Places database.
 *
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places_Country.php file.
 *
 * @module Places
 */
/**
 * Base class representing 'Country' rows in the 'Places' database
 * @class Base_Places_Country
 * @extends Db_Row
 *
 * @param {array} [$fields=array()] The fields values to initialize table row as 
 * an associative array of $column => $value pairs
 * @param {string} [$fields.countryCode] defaults to ""
 * @param {string} [$fields.countryCode3] defaults to null
 * @param {integer} [$fields.geonameId] defaults to 0
 * @param {integer} [$fields.numericCode] defaults to 0
 * @param {string} [$fields.phoneCode] defaults to null
 * @param {string} [$fields.normalizedName] defaults to null
 * @param {string} [$fields.englishName] defaults to null
 * @param {string} [$fields.localName] defaults to null
 * @param {string} [$fields.emojiFlag] defaults to null
 * @param {integer} [$fields.area] defaults to 0
 * @param {integer} [$fields.population] defaults to 0
 * @param {string} [$fields.continent] defaults to null
 * @param {string} [$fields.currencyCode] defaults to null
 * @param {string} [$fields.currencyName] defaults to null
 */
abstract class Base_Places_Country extends Db_Row
{
	/**
	 * @property $countryCode
	 * @type string
	 * @default ""
	 * 
	 */
	/**
	 * @property $countryCode3
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $geonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $numericCode
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $phoneCode
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $normalizedName
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $englishName
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $localName
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $emojiFlag
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $area
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $population
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $continent
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $currencyCode
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $currencyName
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * The setUp() method is called the first time
	 * an object of this class is constructed.
	 * @method setUp
	 */
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'countryCode',
			)
		);
	}

	/**
	 * Connects to database
	 * @method db
	 * @static
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Places');
	}

	/**
	 * Retrieve the table name to use in SQL statement
	 * @method table
	 * @static
	 * @param {boolean} [$with_db_name=true] Indicates wheather table name should contain the database name
	 * @param {string} [$alias=null] You can optionally provide an alias for the table to be used in queries
 	 * @return {string|Db_Expression} The table name as string optionally without database name if no table sharding
	 * was started or Db_Expression class with prefix and database name templates is table was sharded
	 */
	static function table($with_db_name = true, $alias = null)
	{
		if (class_exists('Q_Config') and Q_Config::get('Db', 'connections', 'Places', 'indexes', 'Country', false)) {
			return new Db_Expression(($with_db_name ? '{{dbname}}.' : '').'{{prefix}}'.'country');
		} else {
			$conn = Db::getConnection('Places');
  			$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
  			$table_name = $prefix . 'country';
  			if (!$with_db_name)
  				return $table_name;
  			$db = Db::connect('Places');
			$alias = isset($alias) ? ' '.$alias : '';
  			return $db->dbName().'.'.$table_name.$alias;
		}
	}
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @static
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Places';
	}

	/**
	 * Returns index metadata for the table
	 * @method indexes
	 * @static
	 * @return {array}
	 */
	static function indexes()
	{
		return array (
  'PRIMARY' => 
  array (
    'unique' => true,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'countryCode',
    ),
    'partial' => false,
  ),
  'geonameId' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'geonameId',
    ),
    'partial' => false,
  ),
  'numericCode' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'numericCode',
    ),
    'partial' => false,
  ),
  'area' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'area',
    ),
    'partial' => false,
  ),
  'population' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'population',
    ),
    'partial' => false,
  ),
  'continent' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'continent',
    ),
    'partial' => false,
  ),
  'currencyCode' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'currencyCode',
    ),
    'partial' => false,
  ),
);
	}

	/**
	 * Returns true if a left-prefix index exists for the given columns
	 * @method hasIndexOn
	 * @static
	 * @param {array} $columns
	 * @return {boolean}
	 */
	static function hasIndexOn(array $columns)
	{
		foreach (self::indexes() as $idx) {
			if (array_slice($idx['columns'], 0, count($columns)) === $columns) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Create SELECT query to the class table
	 * @method select
	 * @static
	 * @param {string|array} [$fields=null] The fields as strings, or array of alias=>field.
	 *   The default is to return all fields of the table.
	 * @param {string} [$alias=null] Table alias.
	 * @return {Db_Query} The generated query
	 */
	static function select($fields=null, $alias = null)
	{
		if (!isset($fields)) {
			$fieldNames = array();
			$a = isset($alias) ? $alias.'.' : '';
			foreach (self::fieldNames() as $fn) {
				$fieldNames[] = $a .  $fn;
			}
			$fields = implode(',', $fieldNames);
		}
		$q = self::db()->select($fields, self::table(true, $alias));
		$q->className = 'Places_Country';
		return $q;
	}

	/**
	 * Create UPDATE query to the class table
	 * @method update
	 * @static
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function update($alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->update(self::table(true, $alias));
		$q->className = 'Places_Country';
		return $q;
	}

	/**
	 * Create DELETE query to the class table
	 * @method delete
	 * @static
	 * @param {string} [$table_using=null] If set, adds a USING clause with this table
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function delete($table_using = null, $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->delete(self::table(true, $alias), $table_using);
		$q->className = 'Places_Country';
		return $q;
	}

	/**
	 * Create INSERT query to the class table
	 * @method insert
	 * @static
	 * @param {array} [$fields=array()] The fields as an associative array of column => value pairs
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function insert($fields = array(), $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->insert(self::table(true, $alias), $fields);
		$q->className = 'Places_Country';
		return $q;
	}
	
	/**
	 * Inserts multiple rows into a single table, preparing the statement only once,
	 * and executes all the queries.
	 * @method insertManyAndExecute
	 * @static
	 * @param {array} [$rows=array()] The array of rows to insert. 
	 * (The field names for the prepared statement are taken from the first row.)
	 * You cannot use Db_Expression objects here, because the function binds all parameters with PDO.
	 * @param {array} [$options=array()]
	 *   An associative array of options, including:
	 *
	 * * "chunkSize" {integer} The number of rows to insert at a time. defaults to 20.<br>
	 * * "onDuplicateKeyUpdate" {array} You can put an array of fieldname => value pairs here,
	 * 		which will add an ON DUPLICATE KEY UPDATE clause to the query.
	 *
	 */
	static function insertManyAndExecute($rows = array(), $options = array())
	{
		self::db()->insertManyAndExecute(
			self::table(), $rows,
			array_merge($options, array('className' => 'Places_Country'))
		);
	}
	
	/**
	 * Create raw query with begin clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method begin
	 * @static
	 * @param {string} [$lockType=null] First parameter to pass to query->begin() function
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function begin($lockType = null, $transactionKey = null)
	{
		$q = self::db()->rawQuery('')->begin($lockType, $transactionKey);
		$q->className = 'Places_Country';
		return $q;
	}
	
	/**
	 * Create raw query with commit clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method commit
	 * @static
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function commit($transactionKey = null)
	{
		$q = self::db()->rawQuery('')->commit($transactionKey);
		$q->className = 'Places_Country';
		return $q;
	}
	
	/**
	 * Create raw query with rollback clause
	 * @method rollback
	 * @static
	 * @param {array} $criteria Can be used to target the rollback to some shards.
	 *  Otherwise you'll have to specify shards yourself when calling execute().
	 * @return {Db_Query} The generated query
	 */
	static function rollback()
	{
		$q = self::db()->rawQuery('')->rollback();
		$q->className = 'Places_Country';
		return $q;
	}
	
	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_countryCode
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_countryCode($value)
	{
		if (!isset($value)) {
			$value='';
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('countryCode', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".countryCode");
		if (mb_strlen($value) > 2)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".countryCode");
		return array('countryCode', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the countryCode field
	 * @return {integer}
	 */
	function maxSize_countryCode()
	{

		return 2;			
	}

	/**
	 * Returns schema information for countryCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_countryCode()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '2',
    2 => '',
    3 => false,
  ),
  1 => false,
  2 => 'PRI',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_countryCode3
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_countryCode3($value)
	{
		if (!isset($value)) {
			return array('countryCode3', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('countryCode3', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".countryCode3");
		if (mb_strlen($value) > 3)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".countryCode3");
		return array('countryCode3', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the countryCode3 field
	 * @return {integer}
	 */
	function maxSize_countryCode3()
	{

		return 3;			
	}

	/**
	 * Returns schema information for countryCode3 column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_countryCode3()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '3',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_geonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_geonameId($value)
	{
		if (!isset($value)) {
			return array('geonameId', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('geonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".geonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".geonameId");
		}
		return array('geonameId', $value);			
	}

	/**
	 * @method maxSize_geonameId
	 * Returns the maximum integer that can be assigned to the geonameId field
	 * @return {integer}
	 */
	function maxSize_geonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for geonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_geonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_numericCode
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_numericCode($value)
	{
		if (!isset($value)) {
			return array('numericCode', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('numericCode', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".numericCode");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".numericCode");
		}
		return array('numericCode', $value);			
	}

	/**
	 * @method maxSize_numericCode
	 * Returns the maximum integer that can be assigned to the numericCode field
	 * @return {integer}
	 */
	function maxSize_numericCode()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for numericCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_numericCode()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_phoneCode
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_phoneCode($value)
	{
		if (!isset($value)) {
			return array('phoneCode', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('phoneCode', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".phoneCode");
		if (mb_strlen($value) > 20)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".phoneCode");
		return array('phoneCode', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the phoneCode field
	 * @return {integer}
	 */
	function maxSize_phoneCode()
	{

		return 20;			
	}

	/**
	 * Returns schema information for phoneCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_phoneCode()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '20',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_normalizedName
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_normalizedName($value)
	{
		if (!isset($value)) {
			return array('normalizedName', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('normalizedName', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".normalizedName");
		if (mb_strlen($value) > 180)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".normalizedName");
		return array('normalizedName', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the normalizedName field
	 * @return {integer}
	 */
	function maxSize_normalizedName()
	{

		return 180;			
	}

	/**
	 * Returns schema information for normalizedName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_normalizedName()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '180',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_englishName
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_englishName($value)
	{
		if (!isset($value)) {
			return array('englishName', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('englishName', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".englishName");
		if (mb_strlen($value) > 180)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".englishName");
		return array('englishName', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the englishName field
	 * @return {integer}
	 */
	function maxSize_englishName()
	{

		return 180;			
	}

	/**
	 * Returns schema information for englishName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_englishName()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '180',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_localName
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_localName($value)
	{
		if (!isset($value)) {
			return array('localName', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('localName', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".localName");
		if (mb_strlen($value) > 180)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".localName");
		return array('localName', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the localName field
	 * @return {integer}
	 */
	function maxSize_localName()
	{

		return 180;			
	}

	/**
	 * Returns schema information for localName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_localName()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '180',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_emojiFlag
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_emojiFlag($value)
	{
		if (!isset($value)) {
			return array('emojiFlag', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('emojiFlag', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".emojiFlag");
		if (mb_strlen($value) > 8)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".emojiFlag");
		return array('emojiFlag', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the emojiFlag field
	 * @return {integer}
	 */
	function maxSize_emojiFlag()
	{

		return 8;			
	}

	/**
	 * Returns schema information for emojiFlag column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_emojiFlag()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '8',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_area
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_area($value)
	{
		if (!isset($value)) {
			return array('area', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('area', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".area");
		$value = intval($value);
		if ($value < -9.2233720368548E+18 or $value > 9223372036854775807) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".area");
		}
		return array('area', $value);			
	}

	/**
	 * @method maxSize_area
	 * Returns the maximum integer that can be assigned to the area field
	 * @return {integer}
	 */
	function maxSize_area()
	{

		return 9223372036854775807;			
	}

	/**
	 * Returns schema information for area column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_area()
	{

return array (
  0 => 
  array (
    0 => 'bigint',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_population
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_population($value)
	{
		if (!isset($value)) {
			return array('population', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('population', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".population");
		$value = intval($value);
		if ($value < -9.2233720368548E+18 or $value > 9223372036854775807) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".population");
		}
		return array('population', $value);			
	}

	/**
	 * @method maxSize_population
	 * Returns the maximum integer that can be assigned to the population field
	 * @return {integer}
	 */
	function maxSize_population()
	{

		return 9223372036854775807;			
	}

	/**
	 * Returns schema information for population column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_population()
	{

return array (
  0 => 
  array (
    0 => 'bigint',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_continent
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_continent($value)
	{
		if (!isset($value)) {
			return array('continent', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('continent', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".continent");
		if (mb_strlen($value) > 2)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".continent");
		return array('continent', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the continent field
	 * @return {integer}
	 */
	function maxSize_continent()
	{

		return 2;			
	}

	/**
	 * Returns schema information for continent column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_continent()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '2',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_currencyCode
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_currencyCode($value)
	{
		if (!isset($value)) {
			return array('currencyCode', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('currencyCode', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".currencyCode");
		if (mb_strlen($value) > 3)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".currencyCode");
		return array('currencyCode', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the currencyCode field
	 * @return {integer}
	 */
	function maxSize_currencyCode()
	{

		return 3;			
	}

	/**
	 * Returns schema information for currencyCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_currencyCode()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '3',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_currencyName
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_currencyName($value)
	{
		if (!isset($value)) {
			return array('currencyName', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('currencyName', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".currencyName");
		if (mb_strlen($value) > 64)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".currencyName");
		return array('currencyName', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the currencyName field
	 * @return {integer}
	 */
	function maxSize_currencyName()
	{

		return 64;			
	}

	/**
	 * Returns schema information for currencyName column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_currencyName()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '64',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Check if mandatory fields are set and updates 'magic fields' with appropriate values
	 * @method beforeSave
	 * @param {array} $value The array of fields
	 * @return {array}
	 * @throws {Exception} If mandatory field is not set
	 */
	function beforeSave($value)
	{
		if (!$this->retrieved) {
			$table = $this->getTable();
			foreach (array('countryCode') as $name) {
				if (!isset($value[$name])) {
					throw new Exception("the field $table.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
				}
			}
		}
		if (!isset($this->fields["countryCode"]) and !isset($value["countryCode"])) {
			$this->countryCode = $value["countryCode"] = "";
		}
		return $value;			
	}

	/**
	 * Retrieves field names for class table
	 * @method fieldNames
	 * @static
	 * @param {string} [$table_alias=null] If set, the alieas is added to each field
	 * @param {string} [$field_alias_prefix=null] If set, the method returns associative array of ('prefixed field' => 'field') pairs
	 * @return {array} An array of field names
	 */
	static function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('countryCode', 'countryCode3', 'geonameId', 'numericCode', 'phoneCode', 'normalizedName', 'englishName', 'localName', 'emojiFlag', 'area', 'population', 'continent', 'currencyCode', 'currencyName');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};