<?php

/**
 * Autogenerated base class representing hierarchy rows
 * in the Places database.
 *
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places_Hierarchy.php file.
 *
 * @module Places
 */
/**
 * Base class representing 'Hierarchy' rows in the 'Places' database
 * @class Base_Places_Hierarchy
 * @extends Db_Row
 *
 * @param {array} [$fields=array()] The fields values to initialize table row as 
 * an associative array of $column => $value pairs
 * @param {integer} [$fields.parentGeonameId] defaults to 0
 * @param {integer} [$fields.childGeonameId] defaults to 0
 * @param {integer} [$fields.relationType] defaults to 0
 * @param {string} [$fields.parentType] defaults to null
 * @param {string} [$fields.childType] defaults to null
 */
abstract class Base_Places_Hierarchy extends Db_Row
{
	/**
	 * @property $parentGeonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $childGeonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $relationType
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $parentType
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $childType
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * The setUp() method is called the first time
	 * an object of this class is constructed.
	 * @method setUp
	 */
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'parentGeonameId',
			  1 => 'childGeonameId',
			)
		);
	}

	/**
	 * Connects to database
	 * @method db
	 * @static
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Places');
	}

	/**
	 * Retrieve the table name to use in SQL statement
	 * @method table
	 * @static
	 * @param {boolean} [$with_db_name=true] Indicates wheather table name should contain the database name
	 * @param {string} [$alias=null] You can optionally provide an alias for the table to be used in queries
 	 * @return {string|Db_Expression} The table name as string optionally without database name if no table sharding
	 * was started or Db_Expression class with prefix and database name templates is table was sharded
	 */
	static function table($with_db_name = true, $alias = null)
	{
		if (class_exists('Q_Config') and Q_Config::get('Db', 'connections', 'Places', 'indexes', 'Hierarchy', false)) {
			return new Db_Expression(($with_db_name ? '{{dbname}}.' : '').'{{prefix}}'.'hierarchy');
		} else {
			$conn = Db::getConnection('Places');
  			$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
  			$table_name = $prefix . 'hierarchy';
  			if (!$with_db_name)
  				return $table_name;
  			$db = Db::connect('Places');
			$alias = isset($alias) ? ' '.$alias : '';
  			return $db->dbName().'.'.$table_name.$alias;
		}
	}
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @static
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Places';
	}

	/**
	 * Returns index metadata for the table
	 * @method indexes
	 * @static
	 * @return {array}
	 */
	static function indexes()
	{
		return array (
  'PRIMARY' => 
  array (
    'unique' => true,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'parentGeonameId',
      1 => 'childGeonameId',
    ),
    'partial' => false,
  ),
  'idx_child' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'childGeonameId',
    ),
    'partial' => false,
  ),
  'idx_parent' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'parentGeonameId',
    ),
    'partial' => false,
  ),
  'idx_relation' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'relationType',
    ),
    'partial' => false,
  ),
  'idx_childType' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'childType',
    ),
    'partial' => false,
  ),
  'idx_parentType' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'parentType',
    ),
    'partial' => false,
  ),
);
	}

	/**
	 * Returns true if a left-prefix index exists for the given columns
	 * @method hasIndexOn
	 * @static
	 * @param {array} $columns
	 * @return {boolean}
	 */
	static function hasIndexOn(array $columns)
	{
		foreach (self::indexes() as $idx) {
			if (array_slice($idx['columns'], 0, count($columns)) === $columns) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Create SELECT query to the class table
	 * @method select
	 * @static
	 * @param {string|array} [$fields=null] The fields as strings, or array of alias=>field.
	 *   The default is to return all fields of the table.
	 * @param {string} [$alias=null] Table alias.
	 * @return {Db_Query} The generated query
	 */
	static function select($fields=null, $alias = null)
	{
		if (!isset($fields)) {
			$fieldNames = array();
			$a = isset($alias) ? $alias.'.' : '';
			foreach (self::fieldNames() as $fn) {
				$fieldNames[] = $a .  $fn;
			}
			$fields = implode(',', $fieldNames);
		}
		$q = self::db()->select($fields, self::table(true, $alias));
		$q->className = 'Places_Hierarchy';
		return $q;
	}

	/**
	 * Create UPDATE query to the class table
	 * @method update
	 * @static
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function update($alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->update(self::table(true, $alias));
		$q->className = 'Places_Hierarchy';
		return $q;
	}

	/**
	 * Create DELETE query to the class table
	 * @method delete
	 * @static
	 * @param {string} [$table_using=null] If set, adds a USING clause with this table
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function delete($table_using = null, $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->delete(self::table(true, $alias), $table_using);
		$q->className = 'Places_Hierarchy';
		return $q;
	}

	/**
	 * Create INSERT query to the class table
	 * @method insert
	 * @static
	 * @param {array} [$fields=array()] The fields as an associative array of column => value pairs
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function insert($fields = array(), $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->insert(self::table(true, $alias), $fields);
		$q->className = 'Places_Hierarchy';
		return $q;
	}
	
	/**
	 * Inserts multiple rows into a single table, preparing the statement only once,
	 * and executes all the queries.
	 * @method insertManyAndExecute
	 * @static
	 * @param {array} [$rows=array()] The array of rows to insert. 
	 * (The field names for the prepared statement are taken from the first row.)
	 * You cannot use Db_Expression objects here, because the function binds all parameters with PDO.
	 * @param {array} [$options=array()]
	 *   An associative array of options, including:
	 *
	 * * "chunkSize" {integer} The number of rows to insert at a time. defaults to 20.<br>
	 * * "onDuplicateKeyUpdate" {array} You can put an array of fieldname => value pairs here,
	 * 		which will add an ON DUPLICATE KEY UPDATE clause to the query.
	 *
	 */
	static function insertManyAndExecute($rows = array(), $options = array())
	{
		self::db()->insertManyAndExecute(
			self::table(), $rows,
			array_merge($options, array('className' => 'Places_Hierarchy'))
		);
	}
	
	/**
	 * Create raw query with begin clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method begin
	 * @static
	 * @param {string} [$lockType=null] First parameter to pass to query->begin() function
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function begin($lockType = null, $transactionKey = null)
	{
		$q = self::db()->rawQuery('')->begin($lockType, $transactionKey);
		$q->className = 'Places_Hierarchy';
		return $q;
	}
	
	/**
	 * Create raw query with commit clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method commit
	 * @static
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function commit($transactionKey = null)
	{
		$q = self::db()->rawQuery('')->commit($transactionKey);
		$q->className = 'Places_Hierarchy';
		return $q;
	}
	
	/**
	 * Create raw query with rollback clause
	 * @method rollback
	 * @static
	 * @param {array} $criteria Can be used to target the rollback to some shards.
	 *  Otherwise you'll have to specify shards yourself when calling execute().
	 * @return {Db_Query} The generated query
	 */
	static function rollback()
	{
		$q = self::db()->rawQuery('')->rollback();
		$q->className = 'Places_Hierarchy';
		return $q;
	}
	
	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_parentGeonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_parentGeonameId($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('parentGeonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".parentGeonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".parentGeonameId");
		}
		return array('parentGeonameId', $value);			
	}

	/**
	 * @method maxSize_parentGeonameId
	 * Returns the maximum integer that can be assigned to the parentGeonameId field
	 * @return {integer}
	 */
	function maxSize_parentGeonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for parentGeonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_parentGeonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => false,
  2 => 'PRI',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_childGeonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_childGeonameId($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('childGeonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".childGeonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".childGeonameId");
		}
		return array('childGeonameId', $value);			
	}

	/**
	 * @method maxSize_childGeonameId
	 * Returns the maximum integer that can be assigned to the childGeonameId field
	 * @return {integer}
	 */
	function maxSize_childGeonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for childGeonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_childGeonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => false,
  2 => 'PRI',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_relationType
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_relationType($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('relationType', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".relationType");
		$value = intval($value);
		if ($value < -128 or $value > 127) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".relationType");
		}
		return array('relationType', $value);			
	}

	/**
	 * @method maxSize_relationType
	 * Returns the maximum integer that can be assigned to the relationType field
	 * @return {integer}
	 */
	function maxSize_relationType()
	{

		return 127;			
	}

	/**
	 * Returns schema information for relationType column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_relationType()
	{

return array (
  0 => 
  array (
    0 => 'tinyint',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => false,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value belongs to enum values list
	 * @method beforeSet_parentType
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value does not belong to enum values list
	 */
	function beforeSet_parentType($value)
	{
		if (!isset($value)) {
			return array('parentType', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('parentType', $value);
		}
		if (!in_array($value, array('country','region','district','city','borough')))
			throw new Exception("Out-of-range value '$value' being assigned to ".$this->getTable().".parentType");
		return array('parentType', $value);			
	}

	/**
	 * Returns schema information for parentType column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_parentType()
	{

return array (
  0 => 
  array (
    0 => 'enum',
    1 => '\'country\',\'region\',\'district\',\'city\',\'borough\'',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value belongs to enum values list
	 * @method beforeSet_childType
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value does not belong to enum values list
	 */
	function beforeSet_childType($value)
	{
		if (!isset($value)) {
			return array('childType', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('childType', $value);
		}
		if (!in_array($value, array('country','region','district','city','borough')))
			throw new Exception("Out-of-range value '$value' being assigned to ".$this->getTable().".childType");
		return array('childType', $value);			
	}

	/**
	 * Returns schema information for childType column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_childType()
	{

return array (
  0 => 
  array (
    0 => 'enum',
    1 => '\'country\',\'region\',\'district\',\'city\',\'borough\'',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Check if mandatory fields are set and updates 'magic fields' with appropriate values
	 * @method beforeSave
	 * @param {array} $value The array of fields
	 * @return {array}
	 * @throws {Exception} If mandatory field is not set
	 */
	function beforeSave($value)
	{
		if (!$this->retrieved) {
			$table = $this->getTable();
			foreach (array('parentGeonameId','childGeonameId') as $name) {
				if (!isset($value[$name])) {
					throw new Exception("the field $table.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
				}
			}
		}
		if (!isset($this->fields["parentGeonameId"]) and !isset($value["parentGeonameId"])) {
			$this->parentGeonameId = $value["parentGeonameId"] = 0;
		}
		if (!isset($this->fields["childGeonameId"]) and !isset($value["childGeonameId"])) {
			$this->childGeonameId = $value["childGeonameId"] = 0;
		}
		if (!isset($this->fields["relationType"]) and !isset($value["relationType"])) {
			$this->relationType = $value["relationType"] = 0;
		}
		return $value;			
	}

	/**
	 * Retrieves field names for class table
	 * @method fieldNames
	 * @static
	 * @param {string} [$table_alias=null] If set, the alieas is added to each field
	 * @param {string} [$field_alias_prefix=null] If set, the method returns associative array of ('prefixed field' => 'field') pairs
	 * @return {array} An array of field names
	 */
	static function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('parentGeonameId', 'childGeonameId', 'relationType', 'parentType', 'childType');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};