<?php

/**
 * Autogenerated base class representing ipv4 rows
 * in the Places database.
 *
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places_Ipv4.php file.
 *
 * @module Places
 */
/**
 * Base class representing 'Ipv4' rows in the 'Places' database
 * @class Base_Places_Ipv4
 * @extends Db_Row
 *
 * @param {array} [$fields=array()] The fields values to initialize table row as 
 * an associative array of $column => $value pairs
 * @param {mixed} [$fields.ipMin] defaults to ""
 * @param {mixed} [$fields.ipMax] defaults to ""
 * @param {integer} [$fields.geonameId] defaults to 0
 * @param {string} [$fields.countryCode] defaults to null
 * @param {integer} [$fields.registeredGeonameId] defaults to 0
 * @param {integer} [$fields.representedGeonameId] defaults to 0
 * @param {integer} [$fields.isAnonymousProxy] defaults to 0
 * @param {integer} [$fields.isSatelliteProvider] defaults to 0
 * @param {string} [$fields.postcode] defaults to null
 * @param {float} [$fields.latitude] defaults to 0
 * @param {float} [$fields.longitude] defaults to 0
 * @param {integer} [$fields.accuracy] defaults to 0
 * @param {integer} [$fields.isAnycast] defaults to 0
 */
abstract class Base_Places_Ipv4 extends Db_Row
{
	/**
	 * @property $ipMin
	 * @type mixed
	 * @default ""
	 * 
	 */
	/**
	 * @property $ipMax
	 * @type mixed
	 * @default ""
	 * 
	 */
	/**
	 * @property $geonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $countryCode
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $registeredGeonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $representedGeonameId
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $isAnonymousProxy
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $isSatelliteProvider
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $postcode
	 * @type string
	 * @default null
	 * 
	 */
	/**
	 * @property $latitude
	 * @type float
	 * @default 0
	 * 
	 */
	/**
	 * @property $longitude
	 * @type float
	 * @default 0
	 * 
	 */
	/**
	 * @property $accuracy
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * @property $isAnycast
	 * @type integer
	 * @default 0
	 * 
	 */
	/**
	 * The setUp() method is called the first time
	 * an object of this class is constructed.
	 * @method setUp
	 */
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'ipMin',
			  1 => 'ipMax',
			)
		);
	}

	/**
	 * Connects to database
	 * @method db
	 * @static
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Places');
	}

	/**
	 * Retrieve the table name to use in SQL statement
	 * @method table
	 * @static
	 * @param {boolean} [$with_db_name=true] Indicates wheather table name should contain the database name
	 * @param {string} [$alias=null] You can optionally provide an alias for the table to be used in queries
 	 * @return {string|Db_Expression} The table name as string optionally without database name if no table sharding
	 * was started or Db_Expression class with prefix and database name templates is table was sharded
	 */
	static function table($with_db_name = true, $alias = null)
	{
		if (class_exists('Q_Config') and Q_Config::get('Db', 'connections', 'Places', 'indexes', 'Ipv4', false)) {
			return new Db_Expression(($with_db_name ? '{{dbname}}.' : '').'{{prefix}}'.'ipv4');
		} else {
			$conn = Db::getConnection('Places');
  			$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
  			$table_name = $prefix . 'ipv4';
  			if (!$with_db_name)
  				return $table_name;
  			$db = Db::connect('Places');
			$alias = isset($alias) ? ' '.$alias : '';
  			return $db->dbName().'.'.$table_name.$alias;
		}
	}
	/**
	 * The connection name for the class
	 * @method connectionName
	 * @static
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Places';
	}

	/**
	 * Returns index metadata for the table
	 * @method indexes
	 * @static
	 * @return {array}
	 */
	static function indexes()
	{
		return array (
  'PRIMARY' => 
  array (
    'unique' => true,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'ipMin',
      1 => 'ipMax',
    ),
    'partial' => false,
  ),
  'geonameId' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'geonameId',
    ),
    'partial' => false,
  ),
  'countryCode' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'countryCode',
    ),
    'partial' => false,
  ),
  'postcode' => 
  array (
    'unique' => false,
    'type' => 'btree',
    'columns' => 
    array (
      0 => 'postcode',
    ),
    'partial' => false,
  ),
);
	}

	/**
	 * Returns true if a left-prefix index exists for the given columns
	 * @method hasIndexOn
	 * @static
	 * @param {array} $columns
	 * @return {boolean}
	 */
	static function hasIndexOn(array $columns)
	{
		foreach (self::indexes() as $idx) {
			if (array_slice($idx['columns'], 0, count($columns)) === $columns) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Create SELECT query to the class table
	 * @method select
	 * @static
	 * @param {string|array} [$fields=null] The fields as strings, or array of alias=>field.
	 *   The default is to return all fields of the table.
	 * @param {string} [$alias=null] Table alias.
	 * @return {Db_Query} The generated query
	 */
	static function select($fields=null, $alias = null)
	{
		if (!isset($fields)) {
			$fieldNames = array();
			$a = isset($alias) ? $alias.'.' : '';
			foreach (self::fieldNames() as $fn) {
				$fieldNames[] = $a .  $fn;
			}
			$fields = implode(',', $fieldNames);
		}
		$q = self::db()->select($fields, self::table(true, $alias));
		$q->className = 'Places_Ipv4';
		return $q;
	}

	/**
	 * Create UPDATE query to the class table
	 * @method update
	 * @static
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function update($alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->update(self::table(true, $alias));
		$q->className = 'Places_Ipv4';
		return $q;
	}

	/**
	 * Create DELETE query to the class table
	 * @method delete
	 * @static
	 * @param {string} [$table_using=null] If set, adds a USING clause with this table
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function delete($table_using = null, $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->delete(self::table(true, $alias), $table_using);
		$q->className = 'Places_Ipv4';
		return $q;
	}

	/**
	 * Create INSERT query to the class table
	 * @method insert
	 * @static
	 * @param {array} [$fields=array()] The fields as an associative array of column => value pairs
	 * @param {string} [$alias=null] Table alias
	 * @return {Db_Query} The generated query
	 */
	static function insert($fields = array(), $alias = null)
	{
		$alias = isset($alias) ? ' '.$alias : '';
		$q = self::db()->insert(self::table(true, $alias), $fields);
		$q->className = 'Places_Ipv4';
		return $q;
	}
	
	/**
	 * Inserts multiple rows into a single table, preparing the statement only once,
	 * and executes all the queries.
	 * @method insertManyAndExecute
	 * @static
	 * @param {array} [$rows=array()] The array of rows to insert. 
	 * (The field names for the prepared statement are taken from the first row.)
	 * You cannot use Db_Expression objects here, because the function binds all parameters with PDO.
	 * @param {array} [$options=array()]
	 *   An associative array of options, including:
	 *
	 * * "chunkSize" {integer} The number of rows to insert at a time. defaults to 20.<br>
	 * * "onDuplicateKeyUpdate" {array} You can put an array of fieldname => value pairs here,
	 * 		which will add an ON DUPLICATE KEY UPDATE clause to the query.
	 *
	 */
	static function insertManyAndExecute($rows = array(), $options = array())
	{
		self::db()->insertManyAndExecute(
			self::table(), $rows,
			array_merge($options, array('className' => 'Places_Ipv4'))
		);
	}
	
	/**
	 * Create raw query with begin clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method begin
	 * @static
	 * @param {string} [$lockType=null] First parameter to pass to query->begin() function
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function begin($lockType = null, $transactionKey = null)
	{
		$q = self::db()->rawQuery('')->begin($lockType, $transactionKey);
		$q->className = 'Places_Ipv4';
		return $q;
	}
	
	/**
	 * Create raw query with commit clause
	 * You'll have to specify shards yourself when calling execute().
	 * @method commit
	 * @static
	 * @param {string} [$transactionKey=null] Pass a transactionKey here to "resolve" a previously
	 *  executed that began a transaction with ->begin(). This is to guard against forgetting
	 *  to "resolve" a begin() query with a corresponding commit() or rollback() query
	 *  from code that knows about this transactionKey. Passing a transactionKey that doesn't
	 *  match the latest one on the transaction "stack" also generates an error.
	 *  Passing "*" here matches any transaction key that may have been on the top of the stack.
	 * @return {Db_Query} The generated query
	 */
	static function commit($transactionKey = null)
	{
		$q = self::db()->rawQuery('')->commit($transactionKey);
		$q->className = 'Places_Ipv4';
		return $q;
	}
	
	/**
	 * Create raw query with rollback clause
	 * @method rollback
	 * @static
	 * @param {array} $criteria Can be used to target the rollback to some shards.
	 *  Otherwise you'll have to specify shards yourself when calling execute().
	 * @return {Db_Query} The generated query
	 */
	static function rollback()
	{
		$q = self::db()->rawQuery('')->rollback();
		$q->className = 'Places_Ipv4';
		return $q;
	}
	
	/**
	 * Returns schema information for ipMin column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_ipMin()
	{

return array (
  0 => 
  array (
    0 => 'int unsigned',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => false,
  2 => 'PRI',
  3 => NULL,
);			
	}

	/**
	 * Returns schema information for ipMax column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_ipMax()
	{

return array (
  0 => 
  array (
    0 => 'int unsigned',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => false,
  2 => 'PRI',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_geonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_geonameId($value)
	{
		if (!isset($value)) {
			return array('geonameId', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('geonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".geonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".geonameId");
		}
		return array('geonameId', $value);			
	}

	/**
	 * @method maxSize_geonameId
	 * Returns the maximum integer that can be assigned to the geonameId field
	 * @return {integer}
	 */
	function maxSize_geonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for geonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_geonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_countryCode
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_countryCode($value)
	{
		if (!isset($value)) {
			return array('countryCode', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('countryCode', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".countryCode");
		if (mb_strlen($value) > 2)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".countryCode");
		return array('countryCode', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the countryCode field
	 * @return {integer}
	 */
	function maxSize_countryCode()
	{

		return 2;			
	}

	/**
	 * Returns schema information for countryCode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_countryCode()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '2',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_registeredGeonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_registeredGeonameId($value)
	{
		if (!isset($value)) {
			return array('registeredGeonameId', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('registeredGeonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".registeredGeonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".registeredGeonameId");
		}
		return array('registeredGeonameId', $value);			
	}

	/**
	 * @method maxSize_registeredGeonameId
	 * Returns the maximum integer that can be assigned to the registeredGeonameId field
	 * @return {integer}
	 */
	function maxSize_registeredGeonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for registeredGeonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_registeredGeonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_representedGeonameId
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_representedGeonameId($value)
	{
		if (!isset($value)) {
			return array('representedGeonameId', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('representedGeonameId', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".representedGeonameId");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".representedGeonameId");
		}
		return array('representedGeonameId', $value);			
	}

	/**
	 * @method maxSize_representedGeonameId
	 * Returns the maximum integer that can be assigned to the representedGeonameId field
	 * @return {integer}
	 */
	function maxSize_representedGeonameId()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for representedGeonameId column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_representedGeonameId()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_isAnonymousProxy
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_isAnonymousProxy($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('isAnonymousProxy', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".isAnonymousProxy");
		$value = intval($value);
		if ($value < -128 or $value > 127) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".isAnonymousProxy");
		}
		return array('isAnonymousProxy', $value);			
	}

	/**
	 * @method maxSize_isAnonymousProxy
	 * Returns the maximum integer that can be assigned to the isAnonymousProxy field
	 * @return {integer}
	 */
	function maxSize_isAnonymousProxy()
	{

		return 127;			
	}

	/**
	 * Returns schema information for isAnonymousProxy column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_isAnonymousProxy()
	{

return array (
  0 => 
  array (
    0 => 'tinyint',
    1 => '1',
    2 => '',
    3 => false,
  ),
  1 => false,
  2 => '',
  3 => '0',
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_isSatelliteProvider
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_isSatelliteProvider($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('isSatelliteProvider', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".isSatelliteProvider");
		$value = intval($value);
		if ($value < -128 or $value > 127) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".isSatelliteProvider");
		}
		return array('isSatelliteProvider', $value);			
	}

	/**
	 * @method maxSize_isSatelliteProvider
	 * Returns the maximum integer that can be assigned to the isSatelliteProvider field
	 * @return {integer}
	 */
	function maxSize_isSatelliteProvider()
	{

		return 127;			
	}

	/**
	 * Returns schema information for isSatelliteProvider column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_isSatelliteProvider()
	{

return array (
  0 => 
  array (
    0 => 'tinyint',
    1 => '1',
    2 => '',
    3 => false,
  ),
  1 => false,
  2 => '',
  3 => '0',
);			
	}

	/**
	 * Method is called before setting the field and verifies if value is string of length within acceptable limit.
	 * Optionally accept numeric value which is converted to string
	 * @method beforeSet_postcode
	 * @param {string} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not string or is exceedingly long
	 */
	function beforeSet_postcode($value)
	{
		if (!isset($value)) {
			return array('postcode', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('postcode', $value);
		}
		if (!is_string($value) and !is_numeric($value))
			throw new Exception('Must pass a string to '.$this->getTable().".postcode");
		if (mb_strlen($value) > 20)
			throw new Exception('Exceedingly long value being assigned to '.$this->getTable().".postcode");
		return array('postcode', $value);			
	}

	/**
	 * Returns the maximum string length that can be assigned to the postcode field
	 * @return {integer}
	 */
	function maxSize_postcode()
	{

		return 20;			
	}

	/**
	 * Returns schema information for postcode column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_postcode()
	{

return array (
  0 => 
  array (
    0 => 'varchar',
    1 => '20',
    2 => '',
    3 => false,
  ),
  1 => true,
  2 => 'MUL',
  3 => NULL,
);			
	}

	function beforeSet_latitude($value)
	{
		if (!isset($value)) {
			return array('latitude', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('latitude', $value);
		}
		if (!is_numeric($value))
			throw new Exception('Non-numeric value being assigned to '.$this->getTable().".latitude");
		$value = floatval($value);
		return array('latitude', $value);			
	}

	/**
	 * Returns schema information for latitude column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_latitude()
	{

return array (
  0 => 
  array (
    0 => 'double',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	function beforeSet_longitude($value)
	{
		if (!isset($value)) {
			return array('longitude', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('longitude', $value);
		}
		if (!is_numeric($value))
			throw new Exception('Non-numeric value being assigned to '.$this->getTable().".longitude");
		$value = floatval($value);
		return array('longitude', $value);			
	}

	/**
	 * Returns schema information for longitude column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_longitude()
	{

return array (
  0 => 
  array (
    0 => 'double',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_accuracy
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_accuracy($value)
	{
		if (!isset($value)) {
			return array('accuracy', $value);
		}
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('accuracy', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".accuracy");
		$value = intval($value);
		if ($value < -2147483648 or $value > 2147483647) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".accuracy");
		}
		return array('accuracy', $value);			
	}

	/**
	 * @method maxSize_accuracy
	 * Returns the maximum integer that can be assigned to the accuracy field
	 * @return {integer}
	 */
	function maxSize_accuracy()
	{

		return 2147483647;			
	}

	/**
	 * Returns schema information for accuracy column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_accuracy()
	{

return array (
  0 => 
  array (
    0 => 'int',
    1 => NULL,
    2 => NULL,
    3 => NULL,
  ),
  1 => true,
  2 => '',
  3 => NULL,
);			
	}

	/**
	 * Method is called before setting the field and verifies if integer value falls within allowed limits
	 * @method beforeSet_isAnycast
	 * @param {integer} $value
	 * @return {array} An array of field name and value
	 * @throws {Exception} An exception is thrown if $value is not integer or does not fit in allowed range
	 */
	function beforeSet_isAnycast($value)
	{
		if ($value instanceof Db_Expression
               or $value instanceof Db_Range) {
			return array('isAnycast', $value);
		}
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to '.$this->getTable().".isAnycast");
		$value = intval($value);
		if ($value < -128 or $value > 127) {
			$json = json_encode($value);
			throw new Exception("Out-of-range value $json being assigned to ".$this->getTable().".isAnycast");
		}
		return array('isAnycast', $value);			
	}

	/**
	 * @method maxSize_isAnycast
	 * Returns the maximum integer that can be assigned to the isAnycast field
	 * @return {integer}
	 */
	function maxSize_isAnycast()
	{

		return 127;			
	}

	/**
	 * Returns schema information for isAnycast column
	 * @return {array} [[typeName, displayRange, modifiers, unsigned], isNull, key, default]
	 */
	static function column_isAnycast()
	{

return array (
  0 => 
  array (
    0 => 'tinyint',
    1 => '1',
    2 => '',
    3 => false,
  ),
  1 => false,
  2 => '',
  3 => '0',
);			
	}

	/**
	 * Check if mandatory fields are set and updates 'magic fields' with appropriate values
	 * @method beforeSave
	 * @param {array} $value The array of fields
	 * @return {array}
	 * @throws {Exception} If mandatory field is not set
	 */
	function beforeSave($value)
	{
		if (!$this->retrieved) {
			$table = $this->getTable();
			foreach (array('ipMin','ipMax') as $name) {
				if (!isset($value[$name])) {
					throw new Exception("the field $table.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
				}
			}
		}
		if (!isset($this->fields["ipMin"]) and !isset($value["ipMin"])) {
			$this->ipMin = $value["ipMin"] = "";
		}
		if (!isset($this->fields["ipMax"]) and !isset($value["ipMax"])) {
			$this->ipMax = $value["ipMax"] = "";
		}
		return $value;			
	}

	/**
	 * Retrieves field names for class table
	 * @method fieldNames
	 * @static
	 * @param {string} [$table_alias=null] If set, the alieas is added to each field
	 * @param {string} [$field_alias_prefix=null] If set, the method returns associative array of ('prefixed field' => 'field') pairs
	 * @return {array} An array of field names
	 */
	static function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('ipMin', 'ipMax', 'geonameId', 'countryCode', 'registeredGeonameId', 'representedGeonameId', 'isAnonymousProxy', 'isSatelliteProvider', 'postcode', 'latitude', 'longitude', 'accuracy', 'isAnycast');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};